name: Build and Deploy
on:
  push:
    branches:
      - main
    workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install Devanagari font
        run: |
          sudo mkdir -p /usr/share/fonts/truetype/hind
          sudo cp fonts/Hind-Regular.ttf /usr/share/fonts/truetype/hind/
          sudo fc-cache -f -v  # Refresh font cache
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt 
      - run: mkdocs gh-deploy --force
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PWD: ${{ secrets.BSKY_APP_PWD }}
          DID: ${{ secrets.DID }}
      #- name: Run Post-Deployment Script
      #  run: python post_deploy.py
      #  env:
      #    BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
      #    BSKY_APP_PWD: ${{ secrets.BSKY_APP_PWD }}
      #    DID: ${{ secrets.DID }}
      #    GITHUB_WORKSPACE: ${{ github.workspace }}
      #    SITE_URL: ${{ vars.SITE_URL }}
